vich_uploader:
    db_driver: orm

    mappings:
        cheese_images:
            uri_prefix: '%app.path.cheese_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.cheese_images%'
